In [47]:
import pandas as pd
df = pd.read_csv("taxi_peru.csv", delimiter=';', encoding = "Windows-1251")
df

,journey_id,user_id,driver_id,taxi_id,icon,start_type,start_at,start_lat,start_lon,end_at,end_lat,end_lon,end_state,driver_start_lat,driver_start_lon,arrived_at,source,driver_score,rider_score
0,23a1406fc6a11d866e3c82f22eed4d4c,0e9af5bbf1edfe591b54ecdfd7e91e26,583949a89a9ee17d19e3ca4f137b6b4c,b12f4f09c783e29fe0d0ea624530db56,executive,asap,2010-11-16 16:44:00,"-12,13983536","-77,02355957",2010-11-16 17:29:00,"-12,05537033","-77,0413208",drop off,"-12,10825481","-77,0272739",2010-11-16 17:02:00,iPhone,5.0,5.0
1,dd2af4715d0dc16eded53afc0e243577,a553c46e3a22fb9c326aeb3d72b3334e,NaN,NaN,executive,asap,2010-06-01 00:34:00,"-12,13874817","-76,99536133",2010-06-01 00:37:00,"-12,12465668","-77,02886963",not found,NaN,NaN,NaN,iPhone,NaN,NaN
2,dd91e131888064bf7df3ce08f3d4b4ad,a553c46e3a22fb9c326aeb3d72b3334e,NaN,NaN,executive,asap,2010-05-31 05:01:00,"-12,12453079","-77,02780151",2010-05-31 05:04:00,"-12,13883209","-76,99530029",not found,NaN,NaN,NaN,iPhone,NaN,NaN
3,dd2af4715d0dc16eded53afc0e2466d0,a553c46e3a22fb9c326aeb3d72b3334e,NaN,NaN,executive,asap,2010-06-01 00:29:00,"-12,13885117","-76,99530029",2010-06-01 00:32:00,"-12,12458801","-77,02896118",not found,NaN,NaN,NaN,iPhone,NaN,NaN
4,85b7eabcf5d84e42dc7629b7d27781af,56772d544fdfa589a020a1ff894a86f7,d665fb9f75ef5d9cd0fd89479380ba78,0accdd3aa5a322f4129fa20b53278c69,executive,reserved,2010-09-11 23:55:00,"-12,08995438","-76,92626953",2010-09-12 01:07:00,"-12,02223206","-77,10638428",drop off,"-12,08311558","-76,9277072",2010-09-11 23:50:00,iPhone,4.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23106,4a18ea5737ce0ffecaf20b305a0e2c86,8998bb370b5f0cec43a373adebba0c72,d665fb9f75ef5d9cd0fd89479380ba78,16cbe35db7fff70fbc8251b4cda9fdc9,executive,reserved,2010-07-31 13:15:00,"-12,08974075","-77,04699707",2010-07-31 13:27:00,"-12,08352661","-77,05044556",drop off,"-12,08973527","-77,04787016",2010-07-31 13:15:00,iPhone,5.0,5.0
23107,f1e4317f2c17991dd90d1cd17ae0d399,5f8a6ffef0ea5df78a8ee890267b60ec,17c21284245ff240c7212732991c2373,716a697375634f32a06d692b0448f13d,executive,asap,2010-10-02 05:26:00,"-12,09253011","-77,02875271",2010-10-02 05:56:00,"-12,07776001","-77,05623798",drop off,"-12,10639693","-77,04028948",2010-10-02 05:39:00,Android,NaN,5.0
23108,1e44c0fd0a266c3719ff30410b257bce,c0ffb6f6cd801004dd8609c12277c2d1,4851ee4c867c9b49b909c1adb76c31e9,4851ee4c867c9b49b909c1adb76c538e,executive,asap,2010-09-21 09:56:00,"-12,1275637","-77,02642288",2010-09-21 10:18:00,"-12,10529838","-77,04735249",drop off,"-12,12605017","-77,01882491",2010-09-21 10:05:00,Android,0.0,0.0
23109,7073883383b89ad289e864022150cdd7,c0ffb6f6cd801004dd8609c12277c2d1,56f59b58bcbbd1cdabc3652e713134c2,924d4f0e7554566623e8ebb3904a7b0c,executive,reserved,2010-04-29 04:30:00,"-12,019468","-77,1077669",2010-04-29 05:11:00,"-12,09909987","-77,03475013",drop off,"-12,0710933","-77,09855131",2010-04-29 04:23:00,Android,NaN,5.0
23110,b7dea45c3cc92b9efd5a4905e69ff9bf,c0ffb6f6cd801004dd8609c12277c2d1,924d4f0e7554566623e8ebb390491d08,924d4f0e7554566623e8ebb390491492,executive,asap,2010-03-16 19:58:00,"-12,1334974","-77,0272581",2010-03-16 20:02:00,"-12,029174","-76,93977",rider cancel,"-12,09586711","-77,07372552",NaN,web,NaN,NaN

In [13]:
df.dtypes

journey_id           object
user_id              object
driver_id            object
taxi_id              object
icon                 object
start_type           object
start_at             object
start_lat            object
start_lon            object
end_at               object
end_lat              object
end_lon              object
end_state            object
driver_start_lat     object
driver_start_lon     object
arrived_at           object
source               object
driver_score        float64
rider_score         float64
dtype: object

In [52]:
df = df[(df.end_state != 'not found') & (df.end_state != 'rider cancel') & (df.end_state != 'driver cancel')]
df

,journey_id,user_id,driver_id,taxi_id,icon,start_type,start_at,start_lat,start_lon,end_at,end_lat,end_lon,end_state,driver_start_lat,driver_start_lon,arrived_at,source,driver_score,rider_score
0,23a1406fc6a11d866e3c82f22eed4d4c,0e9af5bbf1edfe591b54ecdfd7e91e26,583949a89a9ee17d19e3ca4f137b6b4c,b12f4f09c783e29fe0d0ea624530db56,executive,asap,2010-11-16 16:44:00,"-12,13983536","-77,02355957",2010-11-16 17:29:00,"-12,05537033","-77,0413208",drop off,"-12,10825481","-77,0272739",2010-11-16 17:02:00,iPhone,5.0,5.0
4,85b7eabcf5d84e42dc7629b7d27781af,56772d544fdfa589a020a1ff894a86f7,d665fb9f75ef5d9cd0fd89479380ba78,0accdd3aa5a322f4129fa20b53278c69,executive,reserved,2010-09-11 23:55:00,"-12,08995438","-76,92626953",2010-09-12 01:07:00,"-12,02223206","-77,10638428",drop off,"-12,08311558","-76,9277072",2010-09-11 23:50:00,iPhone,4.0,5.0
5,2254715f0f569e3173ec61f16cbb8341,56772d544fdfa589a020a1ff894a86f7,baacf396f773709519bbde35a5eab861,baacf396f773709519bbde35a585d91b,executive,reserved,2010-08-10 13:00:00,"-12,02241898","-77,10650635",2010-08-10 14:26:00,"-12,08980179","-76,92608643",drop off,"-12,01706754","-77,05986526",2010-08-10 12:53:00,iPhone,NaN,4.0
6,12432d83b49393bf25164673212b8295,56772d544fdfa589a020a1ff894a86f7,e1332f68e81526e498e4d845233a6d7d,e1332f68e81526e498e4d845235baf80,executive,reserved,2010-08-08 12:10:00,"-12,08995819","-76,9262085",2010-08-08 12:48:00,"-12,02152252","-77,10623169",drop off,"-12,08509125","-76,96944424",2010-08-08 12:01:00,iPhone,5.0,5.0
7,2e51db3a8a77aa594aa686ff19fe6036,56772d544fdfa589a020a1ff894a86f7,d665fb9f75ef5d9cd0fd89479380ba78,0accdd3aa5a322f4129fa20b53278c69,executive,asap,2010-05-16 03:58:00,"-12,11347198","-77,04385376",2010-05-16 04:40:00,"-12,09108734","-76,92266846",drop off,"-12,10828994","-77,03530221",2010-05-16 04:06:00,iPhone,5.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23105,a7b77e5e6e60dc427d96d8d22ac91032,35e7f74c2fbd27db816811036af892e5,406921adcca37705ef527b4246c19db3,406921adcca37705ef527b4246c1a5c6,executive,asap,2010-01-15 20:09:00,"-12,0931795","-77,0716318",2010-01-15 20:51:00,"-12,1215588","-77,0209282",drop off,"-12,0467602","-77,04579661",2010-01-15 20:29:00,web,NaN,5.0
23106,4a18ea5737ce0ffecaf20b305a0e2c86,8998bb370b5f0cec43a373adebba0c72,d665fb9f75ef5d9cd0fd89479380ba78,16cbe35db7fff70fbc8251b4cda9fdc9,executive,reserved,2010-07-31 13:15:00,"-12,08974075","-77,04699707",2010-07-31 13:27:00,"-12,08352661","-77,05044556",drop off,"-12,08973527","-77,04787016",2010-07-31 13:15:00,iPhone,5.0,5.0
23107,f1e4317f2c17991dd90d1cd17ae0d399,5f8a6ffef0ea5df78a8ee890267b60ec,17c21284245ff240c7212732991c2373,716a697375634f32a06d692b0448f13d,executive,asap,2010-10-02 05:26:00,"-12,09253011","-77,02875271",2010-10-02 05:56:00,"-12,07776001","-77,05623798",drop off,"-12,10639693","-77,04028948",2010-10-02 05:39:00,Android,NaN,5.0
23108,1e44c0fd0a266c3719ff30410b257bce,c0ffb6f6cd801004dd8609c12277c2d1,4851ee4c867c9b49b909c1adb76c31e9,4851ee4c867c9b49b909c1adb76c538e,executive,asap,2010-09-21 09:56:00,"-12,1275637","-77,02642288",2010-09-21 10:18:00,"-12,10529838","-77,04735249",drop off,"-12,12605017","-77,01882491",2010-09-21 10:05:00,Android,0.0,0.0
23109,7073883383b89ad289e864022150cdd7,c0ffb6f6cd801004dd8609c12277c2d1,56f59b58bcbbd1cdabc3652e713134c2,924d4f0e7554566623e8ebb3904a7b0c,executive,reserved,2010-04-29 04:30:00,"-12,019468","-77,1077669",2010-04-29 05:11:00,"-12,09909987","-77,03475013",drop off,"-12,0710933","-77,09855131",2010-04-29 04:23:00,Android,NaN,5.0

In [60]:
Sort = df.query("`rider_score` > 4.0")
a = Sort.groupby(['user_id']).agg({'journey_id':'count', 'rider_score':'mean'})
a.sort_values(by=['journey_id', 'rider_score'], ascending=[False, False]).head(5)

                                  journey_id  rider_score
user_id
ae06c34243f741e203e97c48eb42017b         394          5.0
8ed36e0e9dbf62743c06c09e5f7c1835         365          5.0
406921adcca37705ef527b4246c12e83         312          5.0
a86c8d399be95a32f795a8a9887127b9         284          5.0
ae06c34243f741e203e97c48eb62c195         229          5.0

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17698 entries, 0 to 23109
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   journey_id        17698 non-null  object
 1   user_id           17698 non-null  object
 2   driver_id         17437 non-null  object
 3   taxi_id           17437 non-null  object
 4   icon              17698 non-null  object
 5   start_type        17698 non-null  object
 6   start_at          17698 non-null  object
 7   start_lat         17698 non-null  object
 8   start_lon         17698 non-null  object
 9   end_at            17433 non-null  object
 10  end_lat           17698 non-null  object
 11  end_lon           17698 non-null  object
 12  end_state         17686 non-null  object
 13  driver_start_lat  17305 non-null  object
 14  driver_start_lon  17305 non-null  object
 15  arrived_at        17436 non-null  object
 16  source            17600 non-null  object
 17  driver_score      7650 non-null   float64
 18  rider_score       15390 non-null  float64
dtypes: float64(2), object(17)
memory usage: 2.7+ MB

In [74]:

a = df.groupby(['user_id']).agg({'taxi_id':'count', 'driver_id':'count'})
a.sort_values(by=['taxi_id', 'driver_id'], ascending=[False, False]).head(5)

                                  taxi_id  driver_id
user_id
ae06c34243f741e203e97c48eb42017b      447        447
a86c8d399be95a32f795a8a9887127b9      434        434
8ed36e0e9dbf62743c06c09e5f7c1835      416        416
8e37a68fab5f31a5e2c1b5f77c6bb9e5      376        376
406921adcca37705ef527b4246c12e83      343        343

In [69]:
df.taxi_id.unique()

array(['b12f4f09c783e29fe0d0ea624530db56',
       '0accdd3aa5a322f4129fa20b53278c69',
       'baacf396f773709519bbde35a585d91b',
       'e1332f68e81526e498e4d845235baf80',
       'd04f1a596fe4a582f48e6eb2f9e8cceb',
       '406921adcca37705ef527b4246c10d2c',
       '275052e660ff5672db6624c42b67ef9c',
       'e84fda9c5df33f03c89b6923c362193f',
       '3c6f537575929e983585ae9e8648d84a',
       '031fea9628f9238b051a588085333504',
       'bb1e39070cf5a2e2390f00f990d754c9',
       '761737b194876dd53761a03c9591370b',
       '992347d5c59f47b13b14442c6daca5ac',
       '35a17a45aa341b999787fa5e50608f65',
       'f622a9397b85b5c9c0ef938c5d592020',
       '3d68e1172f35c1fbd06db5a1bc38c35f',
       '275052e660ff5672db6624c42b69e770',
       '294e869d187357cad25b8af65aa66c0a',
       '3a9ca0965227dc470f30145e41c974ff',
       '62c2e39787aa19cd2513901cf3b49643',
       'b12f4f09c783e29fe0d0ea62452b9347',
       '2a7979f6826bbbf4a061456c478a7326',
       'f78d50ea4f0c83a4a302d9fa82264b02',
       '2a7979f6826bbbf4a061456c47623b7c',
       'b5ad67a3c92f78510e3bd10d9f4bb83f',
       'fdd18304908a4fa34b8435f2646212b8',
       '1238e44402a93366489cbff9884ba30b',
       'bf42c5e0c312b97496ef6716c857f6e6',
       '6a289f0b5c2f0cb1bc2f7388dfdc2a40',
       'eac81a33ab23504c8ee6373ffc60826c',
       '5f00a946d5717f9c646a53195cfd8d62',
       '57b7491a7db5ce935f85855c193b0f4d',
       'fa5c3d1ad73379ba86b960210e63ee78',
       '78851a91f305d3ed7bb3cc0111e35154',
       'd2f1475850c213560abdec5deae0e32c',
       'bd614a1e34c36eb416c2fb88655c5939',
       '15c2795f9994744f8ffef0a4ba8b94f0',
       '62f21a3c31604c1907882fafee98e804',
       '0fbe7aa8ad7a347abb5748557020ac2a',
       '587ea1ea1ab415acb010ec83082682bf',
       '87586ba0f6d5a6b3999c9e4e412a4a25',
       '358741ec2409c505c4545c38669b16fd', nan,
       '883360491194dd3b866c897b25895c8c',
       '0accdd3aa5a322f4129fa20b532788eb',
       '5ced91860ba5d7fe2859267c89b24c2b',
       '5060ebbf9acef4e4e616e575a3dd4b96',
       '70ba4ba5a1d09c1213940afbf86d5f47',
       'd7baa0261635d7dd15539395bd85364e',
       'fa443c4d6e8a73f8d097f3ed759945d3',
       '634a0374dbf952acf4634b10b7da5ed7',
       '2ca81f8112b8c60af222ee2ed7279f66',
       '6baad006f10a1645d0dca05a23ea4564',
       '8e3b260918554709c6513b53a86cdca6',
       'f4c5ffa2f90baae42f7d30906d2ed5ed',
       '18f48f18ba313b30f2849a5c0af78c62',
       '761737b194876dd53761a03c95043410',
       'ff5c924e0b630fd7c019a423405390be',
       'c26f22be31323781fd478dbcf8926d44',
       'd1500ab3f729689d9866cc67d1c85bcf',
       '1d3c551d7fc3d0daf73f0a8c82781c2d',
       'ec84a73745199ff840ecafcb9283193f',
       '42aa958edf790ef3d45823386fb734ea',
       'b66c43e298753a3d39220e53008a4f19',
       'ba102ab81aaae9437a473f04c2656149',
       'c76f7b7ecd87b555ba34fa076d439cb4',
       'fdd18304908a4fa34b8435f2646224bd',
       '9b22b91f3fa3f39566f27c128022f101',
       '33116cc5bdc176e120b87fd848d3d9aa',
       'c2ed6bdd0113ad6f195e8586932279ba',
       '1d8ba0bdacccf2d0d70ee99251862c54',
       'ccfcfc81abe6485b505ba742749cee55',
       'd7c631184e3e63de9b63154a7e244b9d',
       'd27f6f8da751ea8b93e3e4e429243e1a',
       'ab581e277813d5d9ff98d03b1c761722',
       'f6254a51b033dcea52c37c715b010474',
       'ab6ee368af1a9e1293acc0d14d1f9338',
       '7d696ae0f1d27b6b752121cffbd2a558',
       '36c09cf37ce9cd241ffd160d17af5c0a',
       'f84c35d4d31654b733af0657b05f9b11',
       'ecdcce0c956e266ed26c80fd9e7ec7e8',
       '716a697375634f32a06d692b0428a7f3',
       '72727eaca32690cbede1b205ffa8d810',
       '0fd4a08189ac948f6beaa2d3145c8a83',
       '71fb884c17b72d319a18331d3ee2f8a0',
       'fdd18304908a4fa34b8435f2646221f9',
       'fdd18304908a4fa34b8435f264620c40',
       '12c472dd8efc6ed622ae866925ddd065',
       'f6d984387f19e8b2adf9550ee82502bb',
       '406921adcca37705ef527b4246c045f1',
       'd4253c42617542d43396c0d01e6e078a',
       'fc308d768d77788c726b74fd5e365e1b',
       'fc308d768d77788c726b74fd5e480bb5',
       '275052e660ff5672db6624c42b6833c3',
       '052fe9c7c818906a92de0acdf2f8afa2',
       '1083bcecf6e3df9df65525ec3a6707c5',
       'b862b75318ed157b2e574a204c8f0080',
       '992347d5c59f47b13b14442c6d6e1130',
       '3f33a8c7d52ab10ce75d128c012e0e8c',
       '7bf79d646d318c67421797bb5021b2c5',
       'd4253c42617542d43396c0d01e6c985a',
       'd4253c42617542d43396c0d01e4c1793',
       '992347d5c59f47b13b14442c6d6e1a73',
       '8842ece0c6fb65eb4499f76c51d380b6',
       '5f3cd1befe5e96f2324cfbb14c4d50fc',
       '294e869d187357cad25b8af65aa860e8',
       'ff5c924e0b630fd7c019a423405c86f6',
       '16cbe35db7fff70fbc8251b4cdaa037d',
       '19ab0c811749e07944b0deccb507767e',
       'c31d580a863a6601a97b1b12898445d4',
       '8ff94ac5183d99dc41b042ad5cd7f247',
       'fb81277200c0aea311ad85f90d733b00',
       'a86217dc9fc6e34f29bbbcc6295482c7',
       '684e09fb0761605e25d148f3d3105517',
       'ab6ee368af1a9e1293acc0d14d86f061',
       '294e869d187357cad25b8af65aa3c6b1',
       'ae06c34243f741e203e97c48eb6339ee',
       '883360491194dd3b866c897b258b48ea',
       'eef4aeee867d60d44e1d077d1603c546',
       '0fd4a08189ac948f6beaa2d314e68e64',
       '1d8ba0bdacccf2d0d70ee99251e6b210',
       'bd614a1e34c36eb416c2fb88653c15b6',
       '922d998685f68f17dd0f3c9f36dd51ac',
       'ebd4b0ae48400c6bec1f5909d4d5832d',
       '18f48f18ba313b30f2849a5c0af80ac2',
       '12c472dd8efc6ed622ae8669251b2fa6',
       'f78d50ea4f0c83a4a302d9fa822bd424',
       '6e82410a7a2444e1199e6adb2f5c405b',
       '78851a91f305d3ed7bb3cc0111e343e2',
       'ecad23449871b9851b3730d0b3a50cd6',
       '86e355606daeafe9e3f7a0465b3fdb6a',
       'a7b047c6a09ccb85e9980d80ffaa7cf3',
       '1a63261ffd08f9542093a658c0047b98',
       '395884c1271e80e946d1f02dd92d61c5',
       'af07f9929390d66edf63ab7ee440d4fd',
       '684e09fb0761605e25d148f3d30e2a2e',
       'cd6a65a00f3ac91060d336a9f097f819',
       'ef35302138c34b70ddbeb9a52255d928',
       'b5ad67a3c92f78510e3bd10d9f4c71d8',
       'acf45a789a8ff88fb94179627150d37e',
       'ad9c214e6cfd708d4b41f5b362d6256e',
       '992347d5c59f47b13b14442c6d4dd2fd',
       '86dbbb3cadf803d5670e501a57639040',
       '659fcfb728615b0996641d0399dfd81b',
       '6baad006f10a1645d0dca05a23ea7719',
       '59cbac79f5a653e8a8eb10f0ca291efe',
       'ec84a73745199ff840ecafcb927f3112',
       '992347d5c59f47b13b14442c6dacf82d',
       'b3ba9cda1b124b4fdc5d639f2416c61c',
       'bf0f0845b5094fda2fcdac195eef9327',
       '0ed064de66b8552b422f67f7d2c84462',
       '992347d5c59f47b13b14442c6d8cbcc7',
       'bc5c1ae63a528f0371154594b34877d5',
       'af07f9929390d66edf63ab7ee4406a94',
       '761737b194876dd53761a03c9504f739',
       'd2cf43d9f47c6512b84e1ea7b87503d7',
       '16cbe35db7fff70fbc8251b4cdaa06cb',
       '716a697375634f32a06d692b0448f13d',
       '3e201cdebc5a9c587d83d10ed29e05cf',
       'eef4aeee867d60d44e1d077d1605292e',
       '406921adcca37705ef527b4246c1a5c6',
       'c814db2127582cf95dea1f74f4310a9b',
       '2b9be9ff113177942788e7d6e85526b9',
       '12b8b0215d71ee6b664582bc6de8ba1d',
       '19ab0c811749e07944b0deccb507d16f',
       '924d4f0e7554566623e8ebb3904a7b0c',
       'aba044a086704ad7e9dc66b8c926408d',
       '478419e53317b50cbf9af6b2e35ec463',
       '16cbe35db7fff70fbc8251b4cdca8eb8',
       '593ae49af455f324457edc1472aed026',
       '16cbe35db7fff70fbc8251b4cdcccb70',
       '924d4f0e7554566623e8ebb390491492',
       '0aa51cbf1d21c8c6462dbf0e10027148',
       '1cbe459130a435037ebacaf7fb21861e',
       '16cbe35db7fff70fbc8251b4cda9fdc9',
       '4851ee4c867c9b49b909c1adb76c538e',
       'b68895736389f2949faa8c7355bdb902',
       '54c88ff5110a79082d341066aa44761f',
       '6baad006f10a1645d0dca05a23ea4b4d',
       '2b9be9ff113177942788e7d6e8578d6b',
       'd6d916f7489aba2e893781969ddf3c4c',
       '27c157e605c56c7df70c605963e1c9b7',
       'f8cd07f929f6884cd5fea893f4da3839',
       'a70d782602d74fec18457a2f4dbaab07',
       '04ccf986029fee438f1477120773af40',
       'd7bf644eb441cda6127f91addebb5cd4',
       'b12f4f09c783e29fe0d0ea62452ba688',
       '395884c1271e80e946d1f02dd950b67e',
       '38e92872d3aa0417293e90d813f9bd6d',
       'ff5c924e0b630fd7c019a42340591b2c',
       '54c88ff5110a79082d341066aa4631b8',
       'b1a3f957deba8f50052700bfb28a496a',
       '924d4f0e7554566623e8ebb3902a80f1',
       'e6dc139921090aa5b6e5403899d75cd5',
       'ccfcfc81abe6485b505ba742749ab3fe',
       '593ae49af455f324457edc1472ece6ee',
       '13f9089105129d9278966aaca4a51300',
       'b37083ee004fed8ad304c7606d59f727',
       '4851ee4c867c9b49b909c1adb74cd487',
       '8cb98e46b27af1e6fca8768a2a63fdad',
       '376c68f5428776d661622edd4c847692',
       '406921adcca37705ef527b4246bc16a1',
       '1d6bbc303a2c6584d56322b8ceed495d',
       'f78d50ea4f0c83a4a302d9fa82249a75',
       '2d163dcf6f3e01abf4af5b2a721ecc3a',
       '58af3d0a68980e98b9cc7d5383ec6fcd',
       '9448070ece760ea5386e5d4822361e5c',
       '5a0254807b6014f038fe4157f251d2bc',
       '29c460e9d44ae084d4631c5ade4eea2c',
       '5c2461c42df547d02021de37b2a2abc4',
       'bf0f0845b5094fda2fcdac195ece5ec3'], dtype=object)